### ISSUE TITLE
Man ska inte kunna spara tomma recept

### ISSUE THREAD

**Issue by lisabjo** [karinsandraerika/recipe-app#12]
Som det är nu går det bra att spara recept utan att fylla i något. Vi behöver lägga till en kontroll av att det finns åtminstone ett namn och kanske instruktioner (ingredienser frivilligt). Om de sakerna inte fyllts i när man trycker på Spara ska det inte sparas, och en Toast kan tala om för användaren vad som gäller.

**Comment by karinsandraerika** [comment]
La till en validering för att kontrollera att Namn och ingredienser inte är tomma.
