### ISSUE TITLE
Change layout of read recipe to scrollable, right now the text is outside screen.

### ISSUE THREAD

**Issue by karinsandraerika** [karinsandraerika/recipe-app#13]

**Comment by lisabjo** [comment]
Såg det också. Den som fixar det kanske även kunde lägga till nån liten "avdelare" mellan ingredienser och instruktioner? Typ en linje? Om det går att göra snyggt.

**Comment by karinsandraerika** [comment]
Jag la till rubriker över texten, men en linje utöver det hade nog också varit snyggt. Ska testa.

**Comment by lisabjo** [comment]
Nice. Med rubriker ser åtminstone jag inget behov av avdelare, men testa.
