### ISSUE TITLE
The OnClickListener in adapter listens to the LinearLayout not the CardView 

### ISSUE THREAD

**Issue by EmptyDot** [karinsandraerika/recipe-app#7]
This makes it impossible to click unless you click outside the card

**Comment by karinsandraerika** [comment]
Hmm ska kika på det. Kanske bara ändra layout till vanlig Linear med textview. Just nu har vi väl ändå bara namn på receptet.

**Comment by lisabjo** [comment]
Kika på min RecipeAdapter i sqlite-init-file-branchen för en idé. Plockar ut cardview och sätter onClickListener till den.

**Comment by lisabjo** [comment]
Fixat det.
